/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Trabajadores.frame;


import Transitions.Transition;
import functionExit.Exit;
/**
 *
 * @author jarav
 */
public class RegistrarTrabajador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarTrabajador.class.getName());

    /**
     * Creates new form RegistrarUsuarios
     */
    public RegistrarTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBody = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        mnbOpciones = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mniMenuPrincipal = new javax.swing.JMenuItem();
        mniRealizarVenta = new javax.swing.JMenuItem();
        mniVerDetalleVentas = new javax.swing.JMenuItem();
        mniVerVentasRealizadas = new javax.swing.JMenuItem();
        mniVerUsuarioRegistrado = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Creacion de usuarios");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCedula.setText("Cedula");
        pnlBody.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");
        pnlBody.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblApellidos.setText("Apellidos");
        pnlBody.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        lblRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRol.setText("Rol");
        pnlBody.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        cmbRol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bartender", "Boletería" }));
        pnlBody.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));
        pnlBody.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, -1));
        pnlBody.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 190, -1));
        pnlBody.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 200, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        pnlBody.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuOpciones.setText("Opciones");

        mniMenuPrincipal.setText("Menu Principal");
        mniMenuPrincipal.addActionListener(this::mniMenuPrincipalActionPerformed);
        mnuOpciones.add(mniMenuPrincipal);

        mniRealizarVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniRealizarVenta.setText("Realizar Venta");
        mniRealizarVenta.addActionListener(this::mniRealizarVentaActionPerformed);
        mnuOpciones.add(mniRealizarVenta);

        mniVerDetalleVentas.setText("Ver Detalles de Ventas");
        mniVerDetalleVentas.addActionListener(this::mniVerDetalleVentasActionPerformed);
        mnuOpciones.add(mniVerDetalleVentas);

        mniVerVentasRealizadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniVerVentasRealizadas.setText("Ver Ventas Realizadas");
        mniVerVentasRealizadas.addActionListener(this::mniVerVentasRealizadasActionPerformed);
        mnuOpciones.add(mniVerVentasRealizadas);

        mniVerUsuarioRegistrado.setText("Ver Usuarios Registrados");
        mniVerUsuarioRegistrado.addActionListener(this::mniVerUsuarioRegistradoActionPerformed);
        mnuOpciones.add(mniVerUsuarioRegistrado);

        mnbOpciones.add(mnuOpciones);

        mnuSalir.setText("Salir de la Aplicación");
        mnbOpciones.add(mnuSalir);

        setJMenuBar(mnbOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMenuPrincipalActionPerformed
        // TODO add your handling code here:
                Transition t = new Transition();
        t.registrarTrabajadorToPrincipal(this);
    }//GEN-LAST:event_mniMenuPrincipalActionPerformed

    private void mniRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRealizarVentaActionPerformed
        // TODO add your handling code here:
                        Transition t = new Transition();
        t.registrarTrabajadorToRealizarVenta(this);
    }//GEN-LAST:event_mniRealizarVentaActionPerformed

    private void mniVerDetalleVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVerDetalleVentasActionPerformed
        // TODO add your handling code here:
                        Transition t = new Transition();
        t.registrarTrabajadorToDetalleVenta(this);
    }//GEN-LAST:event_mniVerDetalleVentasActionPerformed

    private void mniVerVentasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVerVentasRealizadasActionPerformed
        // TODO add your handling code here:
                        Transition t = new Transition();
        t.registrarTrabajadorToVentaRealizada(this);
    }//GEN-LAST:event_mniVerVentasRealizadasActionPerformed

    private void mniVerUsuarioRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVerUsuarioRegistradoActionPerformed
        // TODO add your handling code here:
                        Transition t = new Transition();
        t.registrarTrabajadorToVerTrabajadorRegistrado(this);
    }//GEN-LAST:event_mniVerUsuarioRegistradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarTrabajador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JMenuBar mnbOpciones;
    private javax.swing.JMenuItem mniMenuPrincipal;
    private javax.swing.JMenuItem mniRealizarVenta;
    private javax.swing.JMenuItem mniVerDetalleVentas;
    private javax.swing.JMenuItem mniVerUsuarioRegistrado;
    private javax.swing.JMenuItem mniVerVentasRealizadas;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
